version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false" # Mayor seguridad
      - "--entrypoints.web.address=:80"
      - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "8080:8080" # Panel de Traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-net

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portaineryumbo.byronrm.com`)"
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000" # Puerto interno de Portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - proxy-net

  frontend:
    build: ./project-devops-front
    container_name: angular_frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`yumbo.byronrm.com`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=80" # Ajusta si tu nginx/angular interno usa otro puerto (ej. 4200)
    networks:
      - proxy-net

  backend:
    build: ./project-devops-back
    container_name: laravel_backend
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: projectdb
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backyumbo.byronrm.com`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=8000" # Ajusta al puerto que use tu Laravel (ej. 80 o 8000)
    depends_on:
      - db
    networks:
      - proxy-net

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: projectdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - proxy-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgyumbo.byronrm.com`)"
      - "traefik.http.routers.pgadmin.entrypoints=web"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80" # Puerto interno de pgAdmin
    networks:
      - proxy-net

volumes:
  portainer_data:
  postgres_data:

networks:
  proxy-net:
    driver: bridge