name: Deploy to VPS

on:
  push:
    branches:
      - main   # Se ejecuta cuando haces push a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASS }}
          script: |
            cd /root/proyecto
            git pull origin main
            docker-compose down
            docker-compose up -d --build
